runtime: python312
entrypoint: gunicorn -b :$PORT run:app

env: standard

instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
  - url: /static
    static_dir: app/static
  - url: /.*
    script: auto
